services:
  db:
    image: mariadb:11.3.2-jammy
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: Barbearia_ivan
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      TZ: Europe/Bratislava
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"